metadata:
  annotations: 
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: ${project.artifactId}.${ingress.domain}
      http:
        paths:
          - path: /
            backend:
              serviceName: ${project.artifactId}
              servicePort: http
