server:
  port: 8080
  # port: 8443
  # ssl:
  #   key-store-type: PKCS12
  #   key-alias: server
  #   key-password: server
  #   key-store: /home/rgordill/git/customer-service-jdg/customer-service-jdg/server.p12
  #   key-store-password: server
  #   trust-store-type: PKCS12
  #   trust-store: /home/rgordill/git/customer-service-jdg/customer-service-jdg/client.p12
  #   trust-store-password: client
spring:
  main:
    banner-mode: 'off' 
  session:
    store-type: none
  # redis:
  #   host: localhost
  #   port: 6379
  #   password: dIRs5cAAsHIeeRIL
  #   ssl: true
  infinispan:
    embedded:
      enabled: 'true'
      machineId: 
      clusterName:
      configXml:
#   remote:
#     enabled: 'true'
#     server-list: 127.0.0.1:11222
#     use-auth: true
#     auth-username: developer
#     auth-password: dIRs5cAAsHIeeRIL
#     auth-realm: default
#     sasl-mechanism: DIGEST-MD5
#     java-serial-whitelist: .*
# #     marshaller: org.infinispan.commons.marshall.StringMarshaller



